name: init CI/CD

on:
  #  push:
  #    branches:
  #      - "main"

  pull_request:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

# 워크플로우 내에서는 파일 수정, 삭제 불가능. readOnly
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
      #      - name: repo checkout
      #        uses: actions/checkout@v3
      #        with:
      #          submodules: true
      #          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
        shell: bash

      #      - name: Copy application.yml from submodule
      #        run: cp ./blueberry-submodule/application-prod.yml ./src/main/resources/application.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          cd ../../../build/libs
          jar xf blueberry-0.0.1-SNAPSHOT.jar BOOT-INF/classes/application.yml
          cat BOOT-INF/classes/application.yml

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}:latest .
          docker push ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker-compose -f docker-compose.yml down --remove-orphans
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
            docker image prune -f
